// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsJO9Ind-GeauDbagHgCKsoPA73OsSops',
    appId: '1:286137181612:web:94e275bec6950b8b1cc609',
    messagingSenderId: '286137181612',
    projectId: 'placepals-a5221',
    authDomain: 'placepals-a5221.firebaseapp.com',
    storageBucket: 'placepals-a5221.firebasestorage.app',
    measurementId: 'G-MP4NER1L6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVnlnt2-Y8oIcTiSQzNgSfG1eZPmo-DeE',
    appId: '1:286137181612:android:9debeb501bd8beb71cc609',
    messagingSenderId: '286137181612',
    projectId: 'placepals-a5221',
    storageBucket: 'placepals-a5221.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChxkMCJxo0aBuOc0SH2SxckIGqSfK0nho',
    appId: '1:286137181612:ios:7b5513948650546e1cc609',
    messagingSenderId: '286137181612',
    projectId: 'placepals-a5221',
    storageBucket: 'placepals-a5221.firebasestorage.app',
    iosBundleId: 'com.example.placepals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChxkMCJxo0aBuOc0SH2SxckIGqSfK0nho',
    appId: '1:286137181612:ios:7b5513948650546e1cc609',
    messagingSenderId: '286137181612',
    projectId: 'placepals-a5221',
    storageBucket: 'placepals-a5221.firebasestorage.app',
    iosBundleId: 'com.example.placepals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsJO9Ind-GeauDbagHgCKsoPA73OsSops',
    appId: '1:286137181612:web:780a5ef78c02886a1cc609',
    messagingSenderId: '286137181612',
    projectId: 'placepals-a5221',
    authDomain: 'placepals-a5221.firebaseapp.com',
    storageBucket: 'placepals-a5221.firebasestorage.app',
    measurementId: 'G-GQ2DHQLVWF',
  );
}
