// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7ftbsgOres_iX0FcQ4iKBXRFi9yjnpbE',
    appId: '1:330723890500:web:6b70fe1da70cc7a8cef311',
    messagingSenderId: '330723890500',
    projectId: 'placepals24',
    authDomain: 'placepals24.firebaseapp.com',
    storageBucket: 'placepals24.firebasestorage.app',
    measurementId: 'G-R3M1YQ7SSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKBNQqPb6daSgdUOZxmdIqczZ6PpXLpMU',
    appId: '1:330723890500:android:405cca72a4cce21bcef311',
    messagingSenderId: '330723890500',
    projectId: 'placepals24',
    storageBucket: 'placepals24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBosXM4pGi3lCdbEUe1kSeA8B6FDaQo6JI',
    appId: '1:330723890500:ios:3f81dcd9c30d2454cef311',
    messagingSenderId: '330723890500',
    projectId: 'placepals24',
    storageBucket: 'placepals24.firebasestorage.app',
    iosBundleId: 'com.example.placepals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChxkMCJxo0aBuOc0SH2SxckIGqSfK0nho',
    appId: '1:286137181612:ios:7b5513948650546e1cc609',
    messagingSenderId: '286137181612',
    projectId: 'placepals-a5221',
    storageBucket: 'placepals-a5221.firebasestorage.app',
    iosBundleId: 'com.example.placepals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7ftbsgOres_iX0FcQ4iKBXRFi9yjnpbE',
    appId: '1:330723890500:web:b877b50f017e41c3cef311',
    messagingSenderId: '330723890500',
    projectId: 'placepals24',
    authDomain: 'placepals24.firebaseapp.com',
    storageBucket: 'placepals24.firebasestorage.app',
    measurementId: 'G-5D9K8NLEE8',
  );

}